# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7295c8158617acaacbbb31d86ab69a3798393a13f7d5b79f1e2182d182403b3b3c2f32110a7487713db1ca9b78b63041d325293038c6776236b36b014dc2ac68

test:
  secret_key_base: 3b9a4a7408aa07c1a05ff687b6bc00e02574d841f591836ed682dc4ec51c04ce7a2eb583fc5bd47da9b8dd8bb9dc62d7fc12747952b01593be25265caf0c9be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
